In [ ]:
#pd.set_option("display.max_row", None)  #ya value table ma all dehkne ke lie hn keys hn...

In [ ]:
question #no 1: Top 5 players with maximum centuries (in a table)
question #no 2: Top 5 countries with maximum runs count (in a table)
question #no 3: Top 5 players with highest score
question #no 4: Top 5 players with maximum duration in cricket career
question #no5: Top 5 players  with highet six's

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("cricinfo - cricinfo.csv")

In [3]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [ ]:
#df.drop("NO",axis=1)

In [6]:
df.rename(columns={'100':"centuries"},inplace=True)

In [7]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [8]:
df.groupby('Player')['centuries'].sum().sort_values(ascending=False).head(5)

Player
SR Tendulkar (IND)    51
JH Kallis (ICC/SA)    45
RT Ponting (AUS)      41
KC Sangakkara (SL)    38
SPD Smith (AUS)       36
Name: centuries, dtype: int64

In [16]:
df.groupby('Player')['centuries'].sum().sort_values(ascending=False).reset_index().head(5)

               Player  centuries
0  SR Tendulkar (IND)         51
1  JH Kallis (ICC/SA)         45
2    RT Ponting (AUS)         41
3  KC Sangakkara (SL)         38
4     SPD Smith (AUS)         36

In [15]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [10]:
df.groupby('Player')['Runs'].sum().sort_values(ascending=False).head(5)

Player
SR Tendulkar (IND)    15921
RT Ponting (AUS)      13378
JH Kallis (ICC/SA)    13289
R Dravid (ICC/IND)    13288
JE Root (ENG)         12972
Name: Runs, dtype: int64

In [18]:
df.groupby('Player')['Runs'].sum().sort_values(ascending=False).reset_index().head(5)

               Player   Runs
0  SR Tendulkar (IND)  15921
1    RT Ponting (AUS)  13378
2  JH Kallis (ICC/SA)  13289
3  R Dravid (ICC/IND)  13288
4       JE Root (ENG)  12972

In [19]:
df["HS"]=df["HS"].str.split(pat="*").str[0]

In [20]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [27]:
df.groupby("Player")["HS"].sum().sort_values(ascending=False).head(5)

Player
BC Lara (ICC/WI)         400
ML Hayden (AUS)          380
DPMD Jayawardene (SL)    374
GS Sobers (WI)           365
L Hutton (ENG)           364
Name: HS, dtype: object

In [29]:
df.groupby('Player')['HS'].sum().sort_values(ascending=False).reset_index().head(5)

                  Player   HS
0       BC Lara (ICC/WI)  400
1        ML Hayden (AUS)  380
2  DPMD Jayawardene (SL)  374
3         GS Sobers (WI)  365
4         L Hutton (ENG)  364

In [32]:
df.rename(columns={'Span':"career_duration"},inplace=True)

In [33]:
df

,Player,career_duration,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [38]:
df["start_year"]=df["career_duration"].str.split(pat="-").str[0]
df["end_year"]=df["career_duration"].str.split(pat="-").str[1]

In [39]:
df

,Player,career_duration,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s,start_year,end_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           62 non-null     object
 1   career_duration  62 non-null     object
 2   Mat              62 non-null     int64
 3   Inns             62 non-null     int64
 4   NO               62 non-null     int64
 5   Runs             62 non-null     int64
 6   HS               62 non-null     object
 7   Ave              62 non-null     float64
 8   BF               62 non-null     object
 9   SR               62 non-null     object
 10  centuries        62 non-null     int64
 11  50               62 non-null     int64
 12  0                62 non-null     object
 13  4s               62 non-null     int64
 14  6s               62 non-null     int64
 15  start_year       62 non-null     object
 16  end_year         62 non-null     object
dtypes: float64(1), int64(8), object(8)
memory usage: 8.4+ KB

In [42]:
df["start_year"]=df["start_year"].astype(int)
df["end_year"]=df["end_year"].astype(int)

In [43]:
df

,Player,career_duration,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s,start_year,end_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [47]:
df["career_duration"]=df["end_year"]-df["start_year"]

In [48]:
df

,Player,career_duration,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,6s,start_year,end_year,Span
0,DG Bradman (AUS),20,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948,20
1,PHKD Mendis (SL),3,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,2022,2025,3
2,AC Voges (AUS),1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,1
3,RG Pollock (SA),7,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,7
4,GA Headley (WI),24,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,1930,1954,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),16,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,16
58,GC Smith (ICC/SA),12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,12
59,WH Ponsford (AUS),10,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,10
60,SJ McCabe (AUS),8,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,8
61,DR Jardine (ENG),6,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,6

In [51]:
df.groupby("Player")["career_duration"].sum().sort_values(ascending=False).head(5)

Player
GA Headley (WI)       24
SR Tendulkar (IND)    24
JB Hobbs (ENG)        22
S Chanderpaul (WI)    21
DG Bradman (AUS)      20
Name: career_duration, dtype: int64

In [53]:
df.rename(columns={'6s':"sixes"},inplace=True)

In [54]:
df

,Player,career_duration,Mat,Inns,NO,Runs,HS,Ave,BF,SR,centuries,50,0,4s,sixes,start_year,end_year,Span
0,DG Bradman (AUS),20,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948,20
1,PHKD Mendis (SL),3,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,2022,2025,3
2,AC Voges (AUS),1,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,1
3,RG Pollock (SA),7,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,7
4,GA Headley (WI),24,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,1930,1954,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),16,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,16
58,GC Smith (ICC/SA),12,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,12
59,WH Ponsford (AUS),10,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,10
60,SJ McCabe (AUS),8,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,8
61,DR Jardine (ENG),6,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,6

In [57]:
df.groupby('Player')['sixes'].sum().sort_values(ascending=False).head(5)

Player
JH Kallis (ICC/SA)    97
V Sehwag (ICC/IND)    91
BC Lara (ICC/WI)      88
IVA Richards (WI)     84
ML Hayden (AUS)       82
Name: sixes, dtype: int64