In [3]:
import pandas as pd

In [4]:
data={
    'name':["Sabora","Anusha","Rafay","Fatima","Rida","Saba","Mahnoor","Manahil","Huda","Shanzy"],
    'poduct name':["Bags","Mobile","Laptop","Makeup","Shoes","Cooking Dish","Dress","Phone","Computer","Clothes"],
    'sales':[1000,2000,3000,4000,5000,6000,7000,8000,9000,10000]
}

In [5]:
df=pd.DataFrame(data)

In [6]:
df.to_csv("data.csv")

In [7]:
df

      name   poduct name  sales
0   Sabora          Bags   1000
1   Anusha        Mobile   2000
2    Rafay        Laptop   3000
3   Fatima        Makeup   4000
4     Rida         Shoes   5000
5     Saba  Cooking Dish   6000
6  Mahnoor         Dress   7000
7  Manahil         Phone   8000
8     Huda      Computer   9000
9   Shanzy       Clothes  10000

In [8]:
df.where(df['sales']>6000)

      name poduct name    sales
0      NaN         NaN      NaN
1      NaN         NaN      NaN
2      NaN         NaN      NaN
3      NaN         NaN      NaN
4      NaN         NaN      NaN
5      NaN         NaN      NaN
6  Mahnoor       Dress   7000.0
7  Manahil       Phone   8000.0
8     Huda    Computer   9000.0
9   Shanzy     Clothes  10000.0

In [9]:
df.where(df['sales']>6000, other="Not Eligible")

           name   poduct name         sales
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2  Not Eligible  Not Eligible  Not Eligible
3  Not Eligible  Not Eligible  Not Eligible
4  Not Eligible  Not Eligible  Not Eligible
5  Not Eligible  Not Eligible  Not Eligible
6       Mahnoor         Dress          7000
7       Manahil         Phone          8000
8          Huda      Computer          9000
9        Shanzy       Clothes         10000

In [10]:
#df["Category"]=["Accessories","Electronics","Electronics","Cosmetic",""]

In [11]:
df["cogs"]=df["sales"] //1.5

In [12]:
df

      name   poduct name  sales    cogs
0   Sabora          Bags   1000   666.0
1   Anusha        Mobile   2000  1333.0
2    Rafay        Laptop   3000  2000.0
3   Fatima        Makeup   4000  2666.0
4     Rida         Shoes   5000  3333.0
5     Saba  Cooking Dish   6000  4000.0
6  Mahnoor         Dress   7000  4666.0
7  Manahil         Phone   8000  5333.0
8     Huda      Computer   9000  6000.0
9   Shanzy       Clothes  10000  6666.0

In [13]:
#new raw add akrne ke ie

In [16]:
df.loc[len(df)]=["sharafat",5000,"Accessories",5000//1.5]

In [17]:
df

        name   poduct name        sales    cogs
0     Sabora          Bags         1000   666.0
1     Anusha        Mobile         2000  1333.0
2      Rafay        Laptop         3000  2000.0
3     Fatima        Makeup         4000  2666.0
4       Rida         Shoes         5000  3333.0
5       Saba  Cooking Dish         6000  4000.0
6    Mahnoor         Dress         7000  4666.0
7    Manahil         Phone         8000  5333.0
8       Huda      Computer         9000  6000.0
9     Shanzy       Clothes        10000  6666.0
10  sharafat          5000  Accessories  3333.0